import { GluegunCommand } from 'gluegun';
import { safeLoad } from 'js-yaml';

const command: GluegunCommand = {
  name: 'mktree',
  description:
    'Create a directory structure from a yml file or a file generated by the `tree` command',
  run: async toolbox => {
    const {
      print,
      parameters,
      filesystem,
      mktree,
      treeToYaml,
      addVars
    } = toolbox;

    if (!parameters.first || !filesystem.exists(parameters.first)) {
      print.error('Please, specify a file');
      return;
    }

    const filePath = parameters.first;
    const fileData = filesystem.read(filePath);
    const sanitizedFile =
      filePath.endsWith('.yml') || filePath.endsWith('.yaml')
        ? fileData
        : treeToYaml(fileData);

    mktree(safeLoad(addVars(sanitizedFile, parameters.options.var)))
      .then(_ => {
        print.success('Directory Tree created successfully!');
        print.info(fileData);
      })
      .catch(err => print.error(err));
  }
};

module.exports = command;
